name: prbd_2425_a08
description: PRBD - Tricount App (groupe a08)

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  hooks_riverpod: ^2.6.1
  flutter_hooks: ^0.20.5
  jwt_decoder: ^2.0.1
  hive_ce: ^2.6.0
  async: ^2.11.0
  intl: ^0.18.1
  test: ^1.24.0
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
